#!/bin/bash

./qwirkle.exe e2etest --ai < ./tests/ai-new-game/test.input > ./qwirkle.out
if diff -w ./tests/ai-new-game/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi