#!/bin/bash

echo "Running credits test"
chmod +x ./tests/credits/test && ./tests/credits/test &&
echo "Running load-game test"
chmod +x ./tests/load-game/test && ./tests/load-game/test &&
echo "Running new-game test"
chmod +x ./tests/new-game/test && ./tests/new-game/test &&
echo "Running save-game test"
chmod +x ./tests/save-game/test && ./tests/save-game/test &&
echo "Running game-end test"
chmod +x ./tests/game-end/test && ./tests/game-end/test &&
echo "Running qwirkle test"
chmod +x ./tests/qwirkle/test && ./tests/qwirkle/test &&
echo "Running line-validation test"
chmod +x ./tests/line-validation/test && ./tests/line-validation/test &&
echo "Running ai-load-game test"
chmod +x ./tests/ai-load-game/test && ./tests/ai-load-game/test &&
echo "Running ai-new-game test"
chmod +x ./tests/ai-new-game/test && ./tests/ai-new-game/test &&
echo "Running enhanced-new-game test"
chmod +x ./tests/enhanced-new-game/test && ./tests/enhanced-new-game/test;