#!/bin/bash

./qwirkle.exe e2etest --e < ./tests/enhanced-new-game/test.input > ./qwirkle.out
if diff -w ./tests/enhanced-new-game/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi